version: '3'
services:
  node-app:
    container_name: version-one-app-container
    build: 
      context: .
      target: production
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./config.env
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app