version: '3'
services:
  natours-app:
    container_name: version-one-app-container
    build: 
      context: .
      target: production
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./config.env