version: '3'
services:
  natours-app:
    container_name: version-one-app-container
    build: .
    volumes:
      - .:/app:ro
      - /app/node_modules
    ports:
      - "8000:8000"
    env_file:
      - ./config.env